
# -*- coding: utf-8 -*-
"""SaaS Sales Data Analysis to Identify High-Potential Customers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1My4W2UXlninJlONm3fFnES3DXM_eXsgC

# 1. Latar Belakang

Perusahaan Software as a Service (SaaS) B2B menjual produk perangkat lunak kepada pelanggan perusahaan di berbagai wilayah, seperti AMER, APJ, EMEA.

Dalam kegiatan penjualannya, perusahaan melayani berbagai jenis pelanggan, mulai dari SMB dan perusahaan besar lainnya. Setiap pelanggan memiliki nilai transaksi dan tingkat keuntungan yang berbeda-beda.

Permasalahan yang sering terjadi adalah tim penjualan belum mengetahui secara pasti pelanggan mana yang benar-benar memiliki potensi tinggi. Akibatnya, waktu dan usaha sering dihabiskan untuk pelanggan dengan nilai penjualan atau keuntungan yang rendah, bahkan pada beberapa kasus menyebabkan profit yang kecil atau negatif karena pemberian diskon yang terlalu besar.

Dengan memanfaatkan data penjualan SaaS yang tersedia, perusahaan dapat melihat pola berdasarkan wilayah, jenis pelanggan, produk, dan hasil transaksi. Analisis data ini diperlukan untuk membantu perusahaan menentukan prioritas pelanggan yang lebih menguntungkan.

Oleh karena itu, project ini dilakukan untuk menganalisis data penjualan SaaS guna mengidentifikasi pelanggan berpotensi tinggi sebagai dasar pengambilan keputusan dalam proses penjualan.

# 2. Rumusan Masalah

Berdasarkan latar belakang tersebut, rumusan masalah dalam project ini adalah:

1. Bagaimana karakteristik pelanggan SaaS B2B yang memiliki potensi penjualan dan tingkat keuntungan tinggi berdasarkan wilayah, jenis pelanggan, dan produk?

2. Wilayah mana (AMER, APJ, EMEA) yang memberikan kontribusi penjualan dan profit tertinggi bagi perusahaan SaaS?

3. Bagaimana perbedaan nilai transaksi dan profit antara segmen pelanggan SMB dan perusahaan besar?

4. Produk SaaS apa saja yang paling menguntungkan dan paling sering menghasilkan profit rendah akibat diskon?

5. Faktor apa yang paling berpengaruh dalam menentukan pelanggan berpotensi tinggi pada penjualan SaaS B2B?

6. Bagaimana hasil analisis data penjualan dapat digunakan untuk menentukan prioritas pelanggan dalam proses penjualan agar lebih efisien dan menguntungkan?

# 3.  Tujuan Project

Tujuan dari project ini adalah:

1. Menganalisis data penjualan SaaS B2B untuk memahami pola penjualan berdasarkan wilayah, jenis pelanggan, produk, dan hasil transaksi.

2. Mengidentifikasi karakteristik pelanggan yang memiliki potensi penjualan dan tingkat keuntungan tinggi.

3. Mengetahui wilayah, segmen pelanggan, dan produk yang memberikan kontribusi terbesar terhadap pendapatan dan profit perusahaan.

4. Mengidentifikasi faktor-faktor yang menyebabkan profit rendah atau negatif, khususnya yang berkaitan dengan pemberian diskon.

5. Memberikan insight berbasis data sebagai dasar pengambilan keputusan bagi tim penjualan dalam menentukan prioritas pelanggan yang lebih menguntungkan.

# 4.  Data Source

Tahap ini bertujuan untuk memahami struktur, isi, dan karakteristik dataset penjualan SaaS sebelum analisis lebih lanjut dilakukan.

# 4.1 IMPORT LIBRARIES
"""

import pandas as pd # For data manipulation and analysis
import numpy as np # For numerical calculations
import matplotlib.pyplot as plt # For data visualization
import seaborn as sns # For more interesting data visualization
import missingno as msno # For identifying and visualizing missing data
from datetime import datetime # For date manipulation
from scipy import stats
from statsmodels.stats.diagnostic import lilliefors

"""Berikut adalah deskripsi singkat dari setiap pustaka yang diimpor:

Pandas: Digunakan untuk manipulasi dan analisis data berbentuk tabel. Library ini menyediakan struktur data seperti DataFrame yang memudahkan proses pengolahan, pembersihan, dan analisis data.

NumPy: Library untuk komputasi numerik yang digunakan dalam operasi matematika pada array atau matriks serta perhitungan numerik lainnya.

Matplotlib.pyplot: Modul dari Matplotlib yang digunakan untuk membuat visualisasi data, seperti grafik garis, grafik batang, dan grafik sebar (scatter plot).

Seaborn: Library visualisasi data yang dibangun di atas Matplotlib dan digunakan untuk menampilkan grafik yang lebih informatif dan menarik, serta mendukung analisis statistik.

Missingno: Library yang digunakan untuk mengidentifikasi dan memvisualisasikan data yang hilang (missing values) dalam dataset melalui tampilan matriks, heatmap, atau grafik batang.

Datetime: Modul bawaan Python yang digunakan untuk mengelola data waktu dan tanggal, seperti mengubah format tanggal serta menghitung selisih waktu.

# DATA UNDERSTANDING
"""

# Digunakan untuk mengembalikan pengaturan tampilan Pandas ke default
# pd.reset_option('display.max_rows')

# memunculkan semua kolom
pd.set_option('display.max_columns', None)

initialdata = pd.read_csv('SaaS-Sales.csv')
initialdata

"""Data disimpan terlebih dahulu, karena dikhawatirkan data lama akan mengganggu analisis lebih lanjut."""

# Save DataFrame to new CSV file
initialdata.to_csv('SaaS-Sales_new.csv', index=False )#nomor baris tidak ikut disimpan ke file

data = pd.read_csv('SaaS-Sales_new.csv')
data

"""**Penjelasan Kegunaan Setiap Kolom Dataset SaaS Sales :**

Row ID: Nomor urut data (identitas baris).

Order ID: Identitas unik setiap transaksi penjualan.

Order Date: Tanggal terjadinya transaksi penjualan.

Date Key: Format numerik dari tanggal untuk memudahkan analisis waktu.

Contact Name: Nama kontak pelanggan (informasi administratif).

Country: Negara asal pelanggan.

City: Kota pelanggan.

Region: Wilayah pelanggan (AMER, APJ, EMEA) untuk analisis performa penjualan per wilayah.

Subregion: Pembagian wilayah yang lebih detail.

Customer: Nama perusahaan pelanggan.

Customer ID: ID unik pelanggan untuk mencegah duplikasi data.

Industry: Jenis industri pelanggan.

Segment: Segmen pelanggan (SMB atau Enterprise).

Product: Produk SaaS yang dijual.

License: Jenis atau durasi lisensi produk.

Sales: Nilai penjualan (revenue).

Quantity: Jumlah produk atau lisensi yang dibeli.

Discount: Besaran diskon yang diberikan.

Profit: Keuntungan bersih dari transaksi.

Catatan penting bisnis SaaS

Sales ≠ Profit

Profit = Sales - Cost - Discount

Bisa sales tinggi tapi rugi → ini penting buat identifikasi customer potensial

# INFORMATION DATA TYPE
"""

data.info()

"""# CONCLUSSION DATA TYPE

Kesimpulan Data Type Dataset :
Dataset penjualan SaaS memiliki total 9.994 baris dan 19 kolom. Seluruh kolom tidak memiliki missing value (non-null).

Distribusi tipe data:

1. Object (12 kolom)
Digunakan untuk data kategorikal dan teks, seperti: Order ID, Order Date, Contact Name, Country, City, Region, Subregion, Customer, Industry, Segment, Poduct, License.

2. Integer (4 kolom-int64)
Digunakan untuk data numerik diskrit: Row ID, Date Key, Customer ID, Quantity.

3. Float (3 kolom-float64)
Digunakan untuk data numerik kontinu: Sales, Discount, Profit.

# DATA CLEANING

### Ubah Format Tanggal
"""

df = pd.read_csv('SaaS-Sales.csv')
df['Order Date'] = pd.to_datetime(df['Order Date'])

"""## Cek Duplikat"""

df.duplicated().sum()

"""## Cek nilai negatif (valid tapi perlu dicatat)"""

(df['Profit'] < 0).sum()

"""# STATISTIK DESKRIPTIF"""

df[['Sales','Profit','Quantity','Discount']].describe()

"""Rata-rata sales per transaksi

Profit minimum negatif → indikasi promo agresif

Discount max tinggi → potensi margin erosion

# Identifikasi High-Potential Customers (CORE PROJECT)

## Agregasi per Customer
"""

customer_perf = df.groupby(['Customer','Segment','Region']).agg({
    'Sales':'sum',
    'Profit':'sum',
    'Order ID':'nunique',
    'Quantity':'sum'
}).reset_index()

customer_perf.rename(columns={'Order ID':'Total_Orders'}, inplace=True)

"""Definisi High-Potential Customer, Customer dengan:

Total Sales tinggi

Total Profit positif & besar

Order berulang
"""

customer_perf.sort_values(
    by=['Profit','Sales'],
    ascending=False
).head(10)

"""# Data Visualization (Python)

## Distribusi Sales
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,5))
sns.histplot(df['Sales'], bins=30, kde=True)
plt.title('Distribution of Sales')
plt.show()

"""Grafik distribusi sales menunjukkan bahwa sebagian besar transaksi memiliki nilai penjualan yang relatif rendah. Hanya sebagian kecil transaksi yang memiliki nilai sales sangat tinggi, yang ditunjukkan oleh ekor panjang di sisi kanan grafik.

## Profit per Segment
"""

plt.figure(figsize=(8,5))
sns.boxplot(data=df, x='Segment', y='Profit')
plt.title('Profit Distribution by Segment')
plt.show()

"""Grafik profit per segment menunjukkan bahwa setiap segment memiliki variasi profit yang cukup besar. Segment Strategic memiliki potensi keuntungan tertinggi, namun tetap terdapat transaksi yang merugikan. Segment SMB menunjukkan risiko kerugian yang lebih tinggi dibandingkan segment lainnya.

Meskipun beberapa segment menunjukkan potensi profit yang tinggi, masih ditemukan transaksi dengan nilai profit negatif. Oleh karena itu, diperlukan analisis lebih lanjut terhadap customer yang menghasilkan penjualan tinggi namun merugikan.

## 10 Pelanggan Teratas Berdasarkan Keuntungan
"""

top10 = customer_perf.nlargest(10, 'Profit')

plt.figure(figsize=(10,6))
sns.barplot(data=top10, y='Customer', x='Profit')
plt.title('Top 10 Customers by Profit')
plt.show()

"""**Kesimpulan :**

Berdasarkan hasil analisis, customer dengan segment Strategic dan region tertentu menunjukkan kontribusi profit yang signifikan meskipun volume transaksi tidak selalu tinggi. Hal ini menunjukkan bahwa fokus pada customer dengan margin tinggi lebih efektif dibandingkan hanya meningkatkan volume penjualan.

# Customer dengan Penjualan Tinggi tetapi Merugikan
"""

customer_loss = df.groupby('Customer')[['Sales','Profit']].sum().reset_index()

customer_loss = customer_loss[
    (customer_loss['Sales'] > customer_loss['Sales'].median()) &
    (customer_loss['Profit'] < 0)
]

customer_loss.head(10)

"""Sales di atas rata-rata Tapi Profit minus.
Analisis tambahan dilakukan untuk mengidentifikasi customer dengan nilai penjualan tinggi namun menghasilkan keuntungan negatif. Hasil ini menunjukkan bahwa tingginya penjualan tidak selalu berbanding lurus dengan profitabilitas.
"""
